apiVersion: v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
  tier: db
  env: dev
  app: exp-prostgres
ReplicaSet:
  replicas: 3
  spec:
    - image: postgress-dep
      container: postgress:latest
